name: Curso CleanArchiteture em NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Iniciando container"
        run: docker compose up --build -d       

      - uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:3000/customer
          timeout: 120000

      - name: "Executando lint"
        run: docker compose exec -u node app npm run lint

      - name: "Executando testes"
        run: docker compose exec  -u node app npm run test
