name: Curso CleanArchiteture em NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      # need checkout before using compose-action
    - uses: actions/checkout@v3
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docker-compose.yml"
        down-flags: "--volumes"
        services: app
        test-command: "npm run lint"
