name: Curso CleanArchiteture em NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Iniciando container"
        run: docker compose up --build -d

      - name: "Aguardando finalizar npm install"
        run: docker compose exec app wait-for http://localhost:3000/customer -t 120 --

      - name: "Executando lint"
        run: docker compose exec -u node app npm run lint

      - name: "Executando testes"
        run: docker compose exec  -u node app npm run test
